### ISSUE TITLE
Incorrect armSstat_Pub

### ISSUE THREAD

**Issue by mcivar** [xibriz/verisure-mqtt#1]
in vs_publish.py
 #topic = self.armState_pub.format(name=self.overview['armState']['name'].replace(' ', ''))
   topic = self.armState_pub.format(name='RubenAndreassen')

ArmState reported as YOU :)

**Comment by xibriz** [comment]
I have removed name from armState.

Topics looks like this now:

```
verisure/armState/statusType ARMED_HOME
verisure/armState/changedVia REMOTE_APP
```
in stead of
```
verisure/armState/RubenAndreassen/statusType ARMED_HOME
verisure/armState/RubenAndreassen/changedVia REMOTE_APP
```
