### ISSUE TITLE
vacationmode is not published to mqtt

### ISSUE THREAD

**Issue by TheLion** [xibriz/verisure-mqtt#2]
Hi,

The vacationmode status of Verisure is not published to the mqtt.

Is there an easy way to implement this?

Thanks in advance.

**Comment by xibriz** [comment]
Yes, it should be a straight forward job.

I can have a look at it tonight.

**Comment by TheLion** [comment]
Great, thanks!

**Comment by xibriz** [comment]
Added vacation status. Output:

> verisure/vacation/cid 1234567
> verisure/vacation/turnOffPetImmunity False
> verisure/vacation/fromDate 2019-05-01T14:00:00.000Z
> verisure/vacation/toDate 2019-05-31T10:00:00.000Z
> verisure/vacation/temporaryContactName (null)
> verisure/vacation/active False
