### ISSUE TITLE
Issue when having more than one system.

### ISSUE THREAD

**Issue by frankis78** [xibriz/verisure-mqtt#4]
I have added a second system to my account, and now it seems like it pulls the state information from the last system that is added to the account.
Is it possible to update the code and config with system information/innstalation number?
Because i can see from the log that only the state of the last system comes in, and it is not possible to send lock or unlock command to example a doorlock, even if you specify the lock name.

**Comment by xibriz** [comment]
Added attribute for `system name` in config file and support for multiple config files (one for each installation).
