### ISSUE TITLE
Vacationmode (again)

### ISSUE THREAD

**Issue by TheLion** [xibriz/verisure-mqtt#5]
Sorry to bother you, again, about vacationmode.

The script/system, doesn't seem to produce any output any more for vacationmode. I stopped somehwere around june 1st.

All other topics work just fine and produce output, but vacationmode doesn't.

Has something changed on the Verisure side?

**Comment by xibriz** [comment]
I don't know. I have no longer Verisure at my house so I have no way to debug this either.

You could check out the base repository and try to debug the vacation mode from there: https://github.com/persandstrom/python-verisure
